export const SET_RADIUS = "SET_RADIUS";
export const RADIUS_ONCHANG = "RADIUS_ONCHANG";
export const SET_DELTA = "SET_DELTA";
export const LOADING_POINTS = "FETCH_POINTS";
export const SET_LOADING_STATUS = "SET_LOADING_STATUS";
